### PR TITLE
Wildcard ignores

### PR DESCRIPTION
**Pull request by Gon3s**
Add regex ignore like.

### CODE REVIEW

**Comment by flaviocopes** [comment]
I see only the change in the README, is this correct?

**Comment by Gon3s** [comment]
No, 
[here](https://github.com/getgrav/grav-plugin-sitemap/pull/19/commits/90ab4e10522ce8600ba3158c82ba2d3e0c130d43) you can see the 2 change (README and sitemap.php)

**Comment by flaviocopes** [comment]
Seems removed in the second commit: https://github.com/getgrav/grav-plugin-sitemap/pull/19/files

**Comment by rhukster** [comment]
There's no code.. closing

**Pull request closed without merging**
